# Uncomment the next line to define a global platform for your project
# platform :ios, '13.0'


target 'iOS-phone-test' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for iOS-phone-test
	pod 'SnapKit'
	pod 'YYWebImage'
	pod 'FMDB'
	 


end
